version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: fluffy-nginx
    ports:
      - "80:80"      # HTTP 접속용
      - "443:443"    # HTTPS 접속용
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/letsencrypt    # 인증서 저장 경로
      - ./nginx/certbot-etc:/etc/letsencrypt
      - ./nginx/certbot-var:/var/lib/letsencrypt
      - ./nginx/webroot:/var/www/certbot # 인증용 경로
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: fluffy-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: shop
      MYSQL_USER: puppy
      MYSQL_PASSWORD: puppy123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: devhyerin/fluffy-puppy:latest
    container_name: fluffy-puppy
    restart: always
    depends_on:
      - mysql
#    ports:
#      - "80:8080"
    expose:
      - "8080"
    env_file:
      - .env
    environment:
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./uploads:/app/uploads
      - ./uploads:/images

volumes:
  mysql_data:
