version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: fluffy-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: shop
      MYSQL_USER: puppy
      MYSQL_PASSWORD: puppy123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    image: devhyerin/fluffy-puppy:latest
    container_name: fluffy-puppy
    restart: always
    depends_on:
      - mysql
    ports:
      - "80:8080"
    env_file:
      - .env
    environment:
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./uploads:/app/uploads

volumes:
  mysql_data:
